export const GET_9IJA_KIDS = "GET_9IJA_KIDS";
export const FILTER_GAME = "FILTER_GAME";
export const SEARCH_GAME = "SEARCH_GAME";
export const FILTERED_SEARCHED_GAMES = "FILTERED_SEARCHED_GAMES";
